Components:
- component_name: "String spammer 0"
  component_type: "cs_test_0"
  package_name: "my_temoto_ws"
  executable:  "component_string_0"
  output_topics:
    data_type_0: "cs_0_pub_0"
    data_type_1: "cs_0_pub_1"

- component_name: "String spammer 1"
  component_type: "cs_test_1"
  package_name: "my_temoto_ws"
  executable:  "component_string_1"
  input_topics:
    data_type_0: "cs_1_sub_0"
    data_type_1: "cs_1_sub_1"
  output_topics:
    data_type_2: "cs_1_pub_0"
    data_type_3: "cs_1_pub_1"

- component_name: "String spammer 2"
  component_type: "cs_test_2"
  package_name: "my_temoto_ws"
  executable:  "component_string_2"
  input_topics:
    data_type_2: "cs_2_sub_0"
    data_type_3: "cs_2_sub_1"
  output_topics:
    data_type_4: "cs_2_pub_0"
    data_type_5: "cs_2_pub_1"
